# This is a basic workflow to help you get started with Actions

name: EXILED CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: Setup MSBuild
      uses: warrenbuckley/Setup-MSBuild@v1

    # Runs a single command using the runners shell
    - name: Setup Nuget
      uses: warrenbuckley/Setup-Nuget@v1

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2.3.1

    - name: Restore Packages
      run: nuget restore EXILED.sln

    - name: Download references
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: 'https://www.exiled.host/build_deps/References.zip'
        file-name: 'References.zip'

    - name: Download 7zip
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: 'https://www.exiled.host/7za.exe'
        file-name: '7zip.exe'

    - name: Extract Refs
      run: ./7zip.exe e References.zip -obin/Release -r -y

    - name: Build
      env:
        EXILED_REFERENCES: ./References
      run: |
        msbuild EXILED.API -p:Configuration=release
        msbuild Exiled.Bootstrap -p:Configuration=release
        msbuild Exiled.Example -p:Configuration=release
        msbuild Exiled.Loader -p:Configuration=release
        msbuild Exiled.Patcher -p:Configuration=release
        msbuild Exiled.Updater -p:Configuration=release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Build Results
        path: bin/Release

    - name: Upload EXILED Build
      uses: actions/upload-artifact@v2
      with:
        name: EXILED DLLs
        path: bin/Release/Exiled*.dll

